export type AdminField = {
  key: string;
  label: string;
  wide?: boolean;
  type?: "text" | "textarea" | "json";
};

export type AdminSection = {
  title: string;
  fields: AdminField[];
};

export const ADMIN_CONTENT_SECTIONS: Record<string, AdminSection[]> = {
  home: [
    {
      title: "Featured products & chrome",
      fields: [
        { key: "home_store_tag", label: "Featured section tag" },
        { key: "home_store_title", label: "Featured section title" },
        { key: "home_view_all_text", label: "View all button" },
        { key: "home_view_all_link", label: "View all link" },
        { key: "home_search_placeholder", label: "Search placeholder" },
        { key: "home_search_btn", label: "Search button" },
        { key: "home_add_cart", label: "Add to cart" },
        { key: "home_added", label: "Added label" },
        { key: "home_remove", label: "Remove label" },
        { key: "home_hero_tag", label: "Main hero tag" },
        { key: "home_why_tag", label: "Why choose us tag" },
        { key: "home_tagline", label: "Tagline under stats" },
      ],
    },
  ],
  about: [
    {
      title: "Page headers & CTA",
      fields: [
        { key: "about_hero_tag", label: "Hero tag" },
        { key: "about_title_accent", label: "Hero title accent" },
        { key: "about_who_tag", label: "Story section tag" },
        { key: "about_story_title", label: "Story title" },
        { key: "about_story_accent", label: "Story title accent" },
        {
          key: "about_story_html",
          label: "Story extra HTML",
          wide: true,
          type: "textarea",
        },
        { key: "about_values_tag", label: "Values tag" },
        { key: "about_values_title", label: "Values title" },
        { key: "about_values_accent", label: "Values accent" },
        { key: "about_journey_tag", label: "Journey tag" },
        { key: "about_journey_title", label: "Journey title" },
        { key: "about_journey_accent", label: "Journey accent" },
        { key: "about_cta_title", label: "CTA title" },
        {
          key: "about_cta_subtitle",
          label: "CTA subtitle",
          wide: true,
          type: "textarea",
        },
        { key: "about_cta_btn1", label: "CTA primary button" },
        { key: "about_cta_btn1_link", label: "CTA primary link" },
        { key: "about_cta_btn2", label: "CTA secondary button" },
        { key: "about_cta_btn2_link", label: "CTA secondary link" },
      ],
    },
    {
      title: "JSON blocks (stats, points, values, timeline)",
      fields: [
        {
          key: "about_stats_json",
          label: "Stats JSON",
          wide: true,
          type: "json",
        },
        {
          key: "about_points_json",
          label: "Story points JSON",
          wide: true,
          type: "json",
        },
        {
          key: "about_values_json",
          label: "Values JSON",
          wide: true,
          type: "json",
        },
        {
          key: "about_timeline_json",
          label: "Timeline JSON",
          wide: true,
          type: "json",
        },
      ],
    },
  ],
  contact: [
    {
      title: "Page copy",
      fields: [
        { key: "contact_tag", label: "Page tag" },
        { key: "contact_title", label: "Page title" },
        {
          key: "contact_subtitle",
          label: "Page subtitle",
          wide: true,
          type: "textarea",
        },
        { key: "contact_wa_title", label: "WhatsApp card title" },
        { key: "contact_wa_sub", label: "WhatsApp card sub" },
        { key: "contact_tg_title", label: "Telegram card title" },
        { key: "contact_tg_sub", label: "Telegram card sub" },
        { key: "contact_email_title", label: "Email card title" },
        { key: "contact_email_sub", label: "Email card sub" },
        { key: "contact_hours_title", label: "Hours card title" },
        { key: "contact_hours_sub", label: "Hours card sub" },
        { key: "contact_loc_title", label: "Location card title" },
        { key: "contact_loc_sub", label: "Location card sub" },
      ],
    },
    {
      title: "Form labels & messages",
      fields: [
        { key: "contact_form_title", label: "Form title" },
        { key: "contact_lbl_name", label: "Name label" },
        { key: "contact_lbl_email", label: "Email label" },
        { key: "contact_lbl_phone", label: "Phone label" },
        { key: "contact_lbl_subject", label: "Subject label" },
        { key: "contact_lbl_message", label: "Message label" },
        { key: "contact_send", label: "Send button" },
        { key: "contact_sending", label: "Sending button" },
        { key: "contact_success_title", label: "Success title" },
        {
          key: "contact_success_body",
          label: "Success body",
          wide: true,
          type: "textarea",
        },
        {
          key: "contact_error",
          label: "Form error",
          wide: true,
          type: "textarea",
        },
      ],
    },
    {
      title: "Sidebar & FAQ preview",
      fields: [
        { key: "contact_sidebar_wa_title", label: "Sidebar WhatsApp title" },
        {
          key: "contact_sidebar_wa_body",
          label: "Sidebar WhatsApp body",
          wide: true,
          type: "textarea",
        },
        { key: "contact_sidebar_wa_btn", label: "Sidebar WhatsApp button" },
        {
          key: "contact_hours_grid_json",
          label: "Hours grid JSON",
          wide: true,
          type: "json",
        },
        { key: "contact_track_title", label: "Track card title" },
        {
          key: "contact_track_body",
          label: "Track card body",
          wide: true,
          type: "textarea",
        },
        { key: "contact_track_btn", label: "Track button" },
        { key: "contact_track_link", label: "Track link" },
        { key: "contact_faq_tag", label: "FAQ preview tag" },
        { key: "contact_faq_title", label: "FAQ preview title" },
      ],
    },
  ],
  faq: [
    {
      title: "FAQ page",
      fields: [
        { key: "faq_tag", label: "Page tag" },
        { key: "faq_title", label: "Page title" },
        {
          key: "faq_subtitle",
          label: "Page subtitle",
          wide: true,
          type: "textarea",
        },
        { key: "faq_all", label: "All filter label" },
        { key: "faq_loading", label: "Loading text" },
        { key: "faq_empty", label: "Empty text" },
        { key: "faq_help_title", label: "Help section title" },
        {
          key: "faq_help_sub",
          label: "Help section subtitle",
          wide: true,
          type: "textarea",
        },
        { key: "faq_wa_btn", label: "WhatsApp button" },
        { key: "faq_contact_btn", label: "Contact form button" },
        { key: "faq_contact_link", label: "Contact form link" },
      ],
    },
  ],
  footer: [
    {
      title: "Footer links & copy",
      fields: [
        { key: "footer_logo_text", label: "Logo text" },
        { key: "footer_text", label: "Copyright text" },
        { key: "footer_tagline", label: "Tagline" },
        { key: "footer_privacy_text", label: "Privacy link label" },
        { key: "footer_privacy_link", label: "Privacy link URL" },
        { key: "footer_terms_text", label: "Terms link label" },
        { key: "footer_terms_link", label: "Terms link URL" },
        { key: "footer_refund_text", label: "Refund link label" },
        { key: "footer_refund_link", label: "Refund link URL" },
        { key: "footer_faq_text", label: "FAQ link label" },
        { key: "footer_faq_link", label: "FAQ link URL" },
        { key: "social_facebook", label: "Facebook URL" },
        { key: "social_instagram", label: "Instagram URL" },
        { key: "social_youtube", label: "YouTube URL" },
        { key: "social_tiktok", label: "TikTok URL" },
      ],
    },
  ],
  products: [
    {
      title: "Products listing",
      fields: [
        { key: "products_tag", label: "Page tag" },
        { key: "products_title", label: "Page title" },
        {
          key: "products_activation",
          label: "Activation banner",
          wide: true,
          type: "textarea",
        },
        { key: "products_search_placeholder", label: "Search placeholder" },
        { key: "products_filter_all", label: "Filter: All" },
        { key: "products_min_ph", label: "Min price placeholder" },
        { key: "products_max_ph", label: "Max price placeholder" },
        { key: "products_apply", label: "Apply button" },
        { key: "products_sort_featured", label: "Sort: Featured" },
        { key: "products_sort_low", label: "Sort: Low to high" },
        { key: "products_sort_high", label: "Sort: High to low" },
        { key: "products_sort_newest", label: "Sort: Newest" },
        { key: "products_loading", label: "Loading text" },
        { key: "products_error", label: "Error title" },
        {
          key: "products_error_help",
          label: "Error help",
          wide: true,
          type: "textarea",
        },
        { key: "products_retry", label: "Retry button" },
        { key: "products_empty", label: "Empty text" },
        { key: "products_add_cart", label: "Add to cart" },
        { key: "products_added", label: "Added label" },
        { key: "products_remove", label: "Remove label" },
      ],
    },
    {
      title: "Product detail",
      fields: [
        { key: "pd_back", label: "Back link" },
        { key: "pd_not_found", label: "Not found message" },
        { key: "pd_stock_fallback", label: "Stock fallback" },
        { key: "pd_pill_delivery", label: "Trust pill: delivery" },
        { key: "pd_pill_active", label: "Trust pill: active" },
        { key: "pd_pill_uk", label: "Trust pill: UK" },
        {
          key: "pd_activation",
          label: "Activation note",
          wide: true,
          type: "textarea",
        },
        { key: "pd_add_cart", label: "Add to cart" },
        { key: "pd_added", label: "Added label" },
        { key: "pd_remove", label: "Remove label" },
        { key: "pd_view_cart", label: "View cart link text" },
        { key: "pd_view_cart_link", label: "View cart URL" },
        { key: "pd_about_heading", label: "About heading" },
        { key: "pd_included_heading", label: "Included heading" },
      ],
    },
  ],
  cart: [
    {
      title: "Cart, checkout & success",
      fields: [
        { key: "cart_tag", label: "Cart tag" },
        { key: "cart_title", label: "Cart title" },
        { key: "checkout_tag", label: "Checkout tag" },
        { key: "checkout_title", label: "Checkout title" },
        { key: "cart_empty_title", label: "Empty cart title" },
        { key: "cart_empty_body", label: "Empty cart body" },
        { key: "cart_empty_btn", label: "Empty cart button" },
        { key: "cart_empty_link", label: "Empty cart link" },
        { key: "cart_remove", label: "Remove item" },
        { key: "cart_summary", label: "Summary heading" },
        { key: "cart_subtotal", label: "Subtotal label" },
        { key: "cart_shipping", label: "Shipping label" },
        { key: "cart_shipping_free", label: "Free shipping label" },
        { key: "cart_vat_label", label: "VAT display label (text only)" },
        { key: "cart_discount", label: "Discount label" },
        { key: "cart_total", label: "Total label" },
        { key: "cart_coupon_ph", label: "Coupon placeholder" },
        { key: "cart_apply", label: "Apply coupon" },
        { key: "cart_checkout_btn", label: "Proceed to checkout" },
        { key: "cart_details", label: "Details heading" },
        { key: "cart_lbl_name", label: "Name label" },
        { key: "cart_lbl_email", label: "Email label" },
        { key: "cart_lbl_phone", label: "Phone label" },
        { key: "cart_lbl_address", label: "Address label" },
        { key: "cart_lbl_city", label: "City label" },
        { key: "cart_lbl_postcode", label: "Postcode label" },
        { key: "cart_lbl_notes", label: "Notes label" },
        { key: "cart_pay_heading", label: "Payment heading" },
        { key: "cart_pay_bank", label: "Bank transfer label" },
        { key: "cart_pay_bank_sub", label: "Bank transfer sub" },
        { key: "cart_pay_cod", label: "COD label" },
        { key: "cart_pay_cod_sub", label: "COD sub" },
        { key: "bank_heading", label: "Bank details heading" },
        { key: "bank_account_name", label: "Bank account name" },
        { key: "bank_sort_code", label: "Sort code" },
        { key: "bank_account_no", label: "Account number" },
        { key: "bank_reference_value", label: "Reference shown value" },
        { key: "bank_lbl_name", label: "Account name label" },
        { key: "bank_lbl_sort", label: "Sort code label" },
        { key: "bank_lbl_no", label: "Account no label" },
        { key: "bank_lbl_ref", label: "Reference label" },
        { key: "bank_lbl_amount", label: "Amount label" },
        { key: "bank_upload_label", label: "Upload label" },
        { key: "bank_upload_text", label: "Upload text" },
        { key: "bank_ref_input_label", label: "Payment ref input label" },
        { key: "bank_ref_ph", label: "Payment ref placeholder" },
        {
          key: "bank_ref_hint",
          label: "Payment ref hint",
          wide: true,
          type: "textarea",
        },
        { key: "cart_cod_heading", label: "COD heading" },
        { key: "cart_amount_due", label: "Amount due label" },
        { key: "cart_place_order", label: "Place order button" },
        { key: "cart_placing", label: "Placing order button" },
        { key: "cart_back", label: "Back to cart" },
        {
          key: "cart_activation",
          label: "Checkout activation note",
          wide: true,
          type: "textarea",
        },
        { key: "cart_retry", label: "Retry button" },
        { key: "cart_wa_btn", label: "WhatsApp help button" },
        {
          key: "cart_err_unavailable",
          label: "Unavailable error",
          wide: true,
          type: "textarea",
        },
        {
          key: "cart_err_failed",
          label: "Failed error",
          wide: true,
          type: "textarea",
        },
        {
          key: "cart_err_network",
          label: "Network error",
          wide: true,
          type: "textarea",
        },
        { key: "success_none_title", label: "No order title" },
        { key: "success_none_body", label: "No order body" },
        { key: "success_none_btn", label: "No order button" },
        { key: "success_title", label: "Success title" },
        {
          key: "success_body",
          label: "Success body",
          wide: true,
          type: "textarea",
        },
        { key: "success_order_label", label: "Order reference label" },
        { key: "success_items", label: "Order items heading" },
        { key: "success_cost", label: "Cost heading" },
        { key: "success_wa", label: "Success WhatsApp CTA" },
        {
          key: "success_optional",
          label: "Success optional note",
          wide: true,
          type: "textarea",
        },
        { key: "success_track", label: "Track order button" },
        { key: "success_track_link", label: "Track order link" },
      ],
    },
  ],
  tracking: [
    {
      title: "Order tracking",
      fields: [
        { key: "track_tag", label: "Page tag" },
        { key: "track_title", label: "Page title" },
        {
          key: "track_subtitle",
          label: "Subtitle",
          wide: true,
          type: "textarea",
        },
        { key: "track_placeholder", label: "Input placeholder" },
        { key: "track_btn", label: "Track button" },
        { key: "track_searching", label: "Searching button" },
        { key: "track_not_found", label: "Not found message" },
        { key: "track_status_pending", label: "Status: pending" },
        { key: "track_status_confirmed", label: "Status: confirmed" },
        { key: "track_status_dispatched", label: "Status: dispatched" },
        { key: "track_status_delivered", label: "Status: delivered" },
        { key: "track_step1_title", label: "Step 1 title" },
        {
          key: "track_step1_desc",
          label: "Step 1 description",
          wide: true,
          type: "textarea",
        },
        { key: "track_step2_title", label: "Step 2 title" },
        {
          key: "track_step2_desc",
          label: "Step 2 description",
          wide: true,
          type: "textarea",
        },
        { key: "track_step3_title", label: "Step 3 title" },
        {
          key: "track_step3_desc",
          label: "Step 3 description",
          wide: true,
          type: "textarea",
        },
        { key: "track_step4_title", label: "Step 4 title" },
        {
          key: "track_step4_desc",
          label: "Step 4 description",
          wide: true,
          type: "textarea",
        },
        { key: "track_help_title", label: "Help title" },
        {
          key: "track_help_body",
          label: "Help body",
          wide: true,
          type: "textarea",
        },
        { key: "track_wa_btn", label: "WhatsApp button" },
      ],
    },
  ],
  blog: [
    {
      title: "Blog page",
      fields: [
        { key: "blog_tag", label: "Page tag" },
        { key: "blog_title", label: "Page title" },
        {
          key: "blog_subtitle",
          label: "Subtitle",
          wide: true,
          type: "textarea",
        },
        { key: "blog_newsletter_title", label: "Newsletter title" },
        {
          key: "blog_newsletter_sub",
          label: "Newsletter subtitle",
          wide: true,
          type: "textarea",
        },
        { key: "blog_subscribe", label: "Subscribe button" },
        { key: "blog_subscribed", label: "Subscribed message" },
        { key: "blog_read", label: "Read article link" },
        { key: "blog_read_short", label: "Read short link" },
        { key: "blog_back", label: "Back to blog" },
        { key: "blog_not_found", label: "Not found message" },
        { key: "blog_faq_heading", label: "Post FAQ heading" },
        { key: "blog_cta_title", label: "Post CTA title" },
        {
          key: "blog_cta_sub",
          label: "Post CTA subtitle",
          wide: true,
          type: "textarea",
        },
        { key: "blog_cta_btn", label: "Post CTA button" },
        { key: "blog_cta_link", label: "Post CTA link" },
      ],
    },
  ],
  legal: [
    {
      title: "Legal pages (optional HTML body)",
      fields: [
        { key: "privacy_tag", label: "Privacy tag" },
        { key: "privacy_title", label: "Privacy title" },
        { key: "privacy_updated", label: "Privacy updated" },
        {
          key: "privacy_body",
          label: "Privacy body HTML",
          wide: true,
          type: "textarea",
        },
        { key: "terms_tag", label: "Terms tag" },
        { key: "terms_title", label: "Terms title" },
        { key: "terms_updated", label: "Terms updated" },
        {
          key: "terms_body",
          label: "Terms body HTML",
          wide: true,
          type: "textarea",
        },
        { key: "refund_tag", label: "Refund tag" },
        { key: "refund_title", label: "Refund title" },
        { key: "refund_updated", label: "Refund updated" },
        {
          key: "refund_body",
          label: "Refund body HTML",
          wide: true,
          type: "textarea",
        },
        { key: "refund_cta_title", label: "Refund CTA title" },
        {
          key: "refund_cta_sub",
          label: "Refund CTA subtitle",
          wide: true,
          type: "textarea",
        },
        { key: "refund_wa_btn", label: "Refund WhatsApp button" },
        { key: "refund_email_btn", label: "Refund email button" },
      ],
    },
  ],
  global: [
    {
      title: "Global / navbar",
      fields: [
        { key: "nav_logo_alt", label: "Navbar logo alt" },
        { key: "nav_logo_text", label: "Navbar text logo" },
        { key: "nav_cart_label", label: "Navbar cart button" },
        { key: "nav_shop_label", label: "Navbar shop button" },
        { key: "nav_subscription_label", label: "Navbar subscription link" },
        { key: "wa_chat_title", label: "WhatsApp button title" },
      ],
    },
  ],
};

export function keysForPage(page: string): string[] {
  const sections = ADMIN_CONTENT_SECTIONS[page] || [];
  return sections.flatMap((s) => s.fields.map((f) => f.key));
}
