/** Extra CMS keys appended to site_content DEFAULTS. Tuple: key, value, type, page, label */
export const EXTRA_CONTENT_DEFAULTS: Array<[string, string, string, string, string]> = [
  // Global / settings
  ['site_meta_description','Buy Firestick, streaming subscriptions and Android boxes in the UK. Fast delivery, easy setup, real support.','textarea','settings','Default Meta Description'],
  ['nav_logo_alt','Firestick4UK','text','settings','Navbar Logo Alt'],
  ['nav_logo_text','FIRESTICK4UK','text','settings','Navbar Text Logo'],
  ['nav_cart_label','Cart','text','settings','Navbar Cart Button'],
  ['nav_shop_label','Shop Now','text','settings','Navbar Shop Button'],
  ['wa_chat_title','Chat on WhatsApp','text','settings','WhatsApp Button Title'],
  ['social_facebook','','url','settings','Facebook URL'],
  ['social_instagram','','url','settings','Instagram URL'],
  ['social_youtube','','url','settings','YouTube URL'],
  ['social_tiktok','','url','settings','TikTok URL'],
  ['trust_activation','Subscription services are active within 1 hour of payment confirmation.','textarea','settings','Activation Trust Text'],

  // Footer
  ['footer_logo_text','FIRESTICK4UK','text','footer','Footer Logo Text'],
  ['footer_privacy_text','Privacy Policy','text','footer','Privacy Link Label'],
  ['footer_privacy_link','/privacy-policy','text','footer','Privacy Link URL'],
  ['footer_terms_text','Terms & Conditions','text','footer','Terms Link Label'],
  ['footer_terms_link','/terms','text','footer','Terms Link URL'],
  ['footer_refund_text','Refund Policy','text','footer','Refund Link Label'],
  ['footer_refund_link','/refund-policy','text','footer','Refund Link URL'],
  ['footer_faq_text','FAQ','text','footer','FAQ Link Label'],
  ['footer_faq_link','/faq','text','footer','FAQ Link URL'],

  // Home chrome
  ['home_store_tag','Our Store','text','home','Featured Section Tag'],
  ['home_store_title','Featured Products','text','home','Featured Section Title'],
  ['home_view_all_text','View All Products →','text','home','View All Products Label'],
  ['home_view_all_link','/products','text','home','View All Products Link'],
  ['home_search_placeholder','Search products...','text','home','Search Placeholder'],
  ['home_search_btn','Search','text','home','Search Button'],
  ['home_loading','Loading products...','text','home','Products Loading Text'],
  ['home_empty','No products found.','text','home','Products Empty Text'],
  ['home_add_cart','Add to Cart →','text','home','Add to Cart Label'],
  ['home_added','Added!','text','home','Added to Cart Label'],
  ['home_remove','Remove','text','home','Remove from Cart Label'],
  ['home_hero_tag',"UK's #1 Firestick Service",'text','home','Main Hero Tag'],
  ['home_why_tag','Why Choose Us','text','home','Why Choose Us Tag'],

  // About
  ['about_hero_tag','Our Story','text','about','Hero Tag'],
  ['about_title_accent','Tech Store','text','about','Hero Title Accent'],
  ['about_who_tag','Who We Are','text','about','Story Tag'],
  ['about_story_title','Built on','text','about','Story Title'],
  ['about_story_accent','Trust','text','about','Story Title Accent'],
  ['about_story_html','<p>Today, we serve hundreds of customers across the United Kingdom, offering carefully selected Firestick devices, powerful Android boxes, and flexible subscription plans — all backed by our dedicated WhatsApp and Telegram support team.</p><p>Every order is personally handled. No bots. No long waits. Just real people who care about getting you set up quickly and correctly.</p>','textarea','about','Story Extra HTML'],
  ['about_values_tag','What We Stand For','text','about','Values Tag'],
  ['about_values_title','Our','text','about','Values Title'],
  ['about_values_accent','Values','text','about','Values Title Accent'],
  ['about_journey_tag','Our Journey','text','about','Journey Tag'],
  ['about_journey_title','How We','text','about','Journey Title'],
  ['about_journey_accent','Grew','text','about','Journey Title Accent'],
  ['about_cta_title','Ready to Shop With Us?','text','about','CTA Title'],
  ['about_cta_subtitle','Join hundreds of happy UK customers. Fast delivery. Real support.','textarea','about','CTA Subtitle'],
  ['about_cta_btn1','Browse Products','text','about','CTA Primary Button'],
  ['about_cta_btn1_link','/products','text','about','CTA Primary Link'],
  ['about_cta_btn2','Get In Touch','text','about','CTA Secondary Button'],
  ['about_cta_btn2_link','/contact','text','about','CTA Secondary Link'],
  ['about_stats_json','[{"num":"500+","label":"Happy Customers"},{"num":"99%","label":"Satisfaction Rate"},{"num":"24/7","label":"Support Available"},{"num":"2+","label":"Years in Business"},{"num":"1000+","label":"Orders Fulfilled"}]','textarea','about','About Stats JSON'],
  ['about_points_json','[{"icon":"UK","title":"UK Based","desc":"We operate fully within the United Kingdom, serving customers nationwide."},{"icon":"PS","title":"Personal Service","desc":"Every customer gets direct WhatsApp and Telegram support from our team."},{"icon":"FR","title":"Fast & Reliable","desc":"Orders processed and dispatched within 24 hours of confirmation."},{"icon":"FP","title":"Fair Pricing","desc":"No hidden fees. What you see is what you pay."}]','textarea','about','Story Points JSON'],
  ['about_values_json','[{"icon":"TR","title":"Transparency","desc":"No hidden charges, no confusing terms. We tell you exactly what you are getting before you buy."},{"icon":"SP","title":"Speed","desc":"Fast order processing, quick delivery, and instant support responses — we value your time."},{"icon":"RS","title":"Real Support","desc":"Our WhatsApp and Telegram team is staffed by real humans who know our products inside out."},{"icon":"QL","title":"Quality","desc":"We only sell devices and plans we trust and have tested ourselves."},{"icon":"RL","title":"Reliability","desc":"We follow through on every promise — from delivery times to after-sales support."},{"icon":"VL","title":"Value","desc":"Premium products at fair prices. We believe quality should not cost a fortune."}]','textarea','about','Values JSON'],
  ['about_timeline_json','[{"year":"2022","icon":"01","title":"Founded","desc":"Firestick4UK launched with a small range of Firestick devices and a big ambition to serve UK customers better."},{"year":"2023","icon":"02","title":"Expanded Products","desc":"Added Android boxes and flexible subscription plans to our catalogue based on customer demand."},{"year":"2024","icon":"03","title":"WhatsApp Support Launched","desc":"Introduced dedicated WhatsApp and Telegram support, making us one of the most responsive tech stores in the UK."},{"year":"2025","icon":"04","title":"500+ Happy Customers","desc":"Reached a major milestone of 500 satisfied customers with a 99% satisfaction rate."},{"year":"2026","icon":"05","title":"New Website Launch","desc":"Launched our brand new custom-built website with full order tracking and easy payment options."}]','textarea','about','Timeline JSON'],

  // Contact
  ['contact_tag','Get In Touch','text','contact','Page Tag'],
  ['contact_title','Contact Us','text','contact','Page Title'],
  ['contact_subtitle','Have a question or need help? We are here for you — reach out anytime.','textarea','contact','Page Subtitle'],
  ['contact_wa_title','WhatsApp','text','contact','WhatsApp Card Title'],
  ['contact_wa_sub','Fastest response','text','contact','WhatsApp Card Sub'],
  ['contact_tg_title','Telegram','text','contact','Telegram Card Title'],
  ['contact_tg_sub','Message us anytime','text','contact','Telegram Card Sub'],
  ['contact_email_title','Email','text','contact','Email Card Title'],
  ['contact_email_sub','Reply within 24 hours','text','contact','Email Card Sub'],
  ['contact_hours_title','Support Hours','text','contact','Hours Card Title'],
  ['contact_hours_sub','7 days a week','text','contact','Hours Card Sub'],
  ['contact_loc_title','Based In','text','contact','Location Card Title'],
  ['contact_loc_sub','UK based support','text','contact','Location Card Sub'],
  ['contact_form_title','Send Us a Message','text','contact','Form Title'],
  ['contact_lbl_name','Your Name *','text','contact','Name Label'],
  ['contact_lbl_email','Email *','text','contact','Email Label'],
  ['contact_lbl_phone','Phone / WhatsApp','text','contact','Phone Label'],
  ['contact_lbl_subject','Subject','text','contact','Subject Label'],
  ['contact_lbl_message','Message *','text','contact','Message Label'],
  ['contact_send','Send Message →','text','contact','Send Button'],
  ['contact_sending','Sending...','text','contact','Sending Button'],
  ['contact_success_title','Message Sent!','text','contact','Success Title'],
  ['contact_success_body','Thank you for reaching out. We will get back to you within 24 hours. For urgent queries, please WhatsApp us or message us on Telegram directly.','textarea','contact','Success Body'],
  ['contact_error','Failed to send message. Please try WhatsApp or Telegram instead.','textarea','contact','Form Error'],
  ['contact_sidebar_wa_title','WhatsApp Support','text','contact','Sidebar WhatsApp Title'],
  ['contact_sidebar_wa_body','Send us a message on WhatsApp or Telegram for instant support. We typically reply within minutes during business hours.','textarea','contact','Sidebar WhatsApp Body'],
  ['contact_sidebar_wa_btn','Chat Now on WhatsApp →','text','contact','Sidebar WhatsApp Button'],
  ['contact_hours_grid_json','[{"day":"Monday – Friday","hours":"9AM – 10PM"},{"day":"Saturday","hours":"10AM – 8PM"},{"day":"Sunday","hours":"11AM – 6PM"},{"day":"Bank Holidays","hours":"Limited hours"}]','textarea','contact','Hours Grid JSON'],
  ['contact_track_title','Track Your Order','text','contact','Track Card Title'],
  ['contact_track_body','Already placed an order? Use your Order ID to check your delivery status in real time.','textarea','contact','Track Card Body'],
  ['contact_track_btn','Track Order →','text','contact','Track Card Button'],
  ['contact_track_link','/order-tracking','text','contact','Track Card Link'],
  ['contact_faq_tag','Quick Answers','text','contact','FAQ Preview Tag'],
  ['contact_faq_title','Frequently Asked Questions','text','contact','FAQ Preview Title'],

  // FAQ page
  ['faq_tag','Help Centre','text','faq','Page Tag'],
  ['faq_title','Frequently Asked Questions','text','faq','Page Title'],
  ['faq_subtitle','Find answers to the most common questions about our products and services.','textarea','faq','Page Subtitle'],
  ['faq_all','All','text','faq','All Filter Label'],
  ['faq_loading','Loading FAQs...','text','faq','Loading Text'],
  ['faq_empty','No FAQs available yet.','text','faq','Empty Text'],
  ['faq_help_title','Still Need Help?','text','faq','Help Title'],
  ['faq_help_sub','Cannot find the answer you are looking for? Our team is happy to help.','textarea','faq','Help Subtitle'],
  ['faq_wa_btn','WhatsApp Us','text','faq','WhatsApp Button'],
  ['faq_contact_btn','Contact Form','text','faq','Contact Form Button'],
  ['faq_contact_link','/contact','text','faq','Contact Form Link'],

  // Products listing
  ['products_tag','Our Store','text','products','Page Tag'],
  ['products_title','All Products','text','products','Page Title'],
  ['products_activation','Subscription services are active within 1 hour of payment confirmation. Need help? WhatsApp {phone} or Telegram {telegram}.','textarea','products','Activation Banner'],
  ['products_search_placeholder','Search products...','text','products','Search Placeholder'],
  ['products_filter_all','All','text','products','Filter All'],
  ['products_min_ph','Min £','text','products','Min Price Placeholder'],
  ['products_max_ph','Max £','text','products','Max Price Placeholder'],
  ['products_apply','Apply','text','products','Apply Button'],
  ['products_sort_featured','Featured','text','products','Sort Featured'],
  ['products_sort_low','Price: Low → High','text','products','Sort Low'],
  ['products_sort_high','Price: High → Low','text','products','Sort High'],
  ['products_sort_newest','Newest','text','products','Sort Newest'],
  ['products_loading','Loading products...','text','products','Loading Text'],
  ['products_error','Could not load products right now.','text','products','Error Title'],
  ['products_error_help','Please try again in a moment or contact us via WhatsApp or Telegram {telegram}.','textarea','products','Error Help'],
  ['products_retry','Try Again','text','products','Retry Button'],
  ['products_empty','No products found.','text','products','Empty Text'],
  ['products_add_cart','Add to Cart →','text','products','Add to Cart'],
  ['products_added','Added!','text','products','Added Label'],
  ['products_remove','Remove','text','products','Remove Label'],
  ['products_meta_title','Products — Firestick4UK | Streaming Devices UK','text','products','Meta Title'],
  ['products_meta_description','Browse our full range of Firestick devices, Android boxes and streaming subscriptions in the UK.','textarea','products','Meta Description'],

  // Product detail
  ['pd_back','← Back to Products','text','products','Back Link'],
  ['pd_not_found','Product not found. Browse all products →','text','products','Not Found'],
  ['pd_stock_fallback','In Stock','text','products','Stock Fallback'],
  ['pd_pill_delivery','Fast Delivery','text','products','Trust Pill Delivery'],
  ['pd_pill_active','Active within 1 hour','text','products','Trust Pill Active'],
  ['pd_pill_uk','UK Based','text','products','Trust Pill UK'],
  ['pd_activation','Subscription services are active within 1 hour of payment confirmation. Need help? WhatsApp {phone} or Telegram {telegram}.','textarea','products','Detail Activation Note'],
  ['pd_add_cart','Add to Cart →','text','products','Detail Add to Cart'],
  ['pd_added','Added to Cart!','text','products','Detail Added'],
  ['pd_remove','Remove from Cart','text','products','Detail Remove'],
  ['pd_view_cart','View Cart & Checkout →','text','products','View Cart Link'],
  ['pd_view_cart_link','/cart','text','products','View Cart URL'],
  ['pd_about_heading','About This Product','text','products','About Heading'],
  ['pd_included_heading','What\'s Included','text','products','Included Heading'],

  // Cart / checkout
  ['cart_tag','Your Cart','text','cart','Cart Tag'],
  ['cart_title','My Cart','text','cart','Cart Title'],
  ['checkout_tag','Checkout','text','cart','Checkout Tag'],
  ['checkout_title','Complete Order','text','cart','Checkout Title'],
  ['cart_empty_title','Your cart is empty','text','cart','Empty Title'],
  ['cart_empty_body','Add some products to get started!','text','cart','Empty Body'],
  ['cart_empty_btn','Browse Products','text','cart','Empty Button'],
  ['cart_empty_link','/products','text','cart','Empty Button Link'],
  ['cart_remove','Remove','text','cart','Remove Item'],
  ['cart_summary','Order Summary','text','cart','Summary Heading'],
  ['cart_subtotal','Subtotal','text','cart','Subtotal Label'],
  ['cart_shipping','Shipping','text','cart','Shipping Label'],
  ['cart_shipping_free','Free','text','cart','Free Shipping Label'],
  ['cart_vat_label','VAT (20%)','text','cart','VAT Display Label'],
  ['cart_discount','Discount','text','cart','Discount Label'],
  ['cart_total','Total','text','cart','Total Label'],
  ['cart_coupon_ph','Coupon code','text','cart','Coupon Placeholder'],
  ['cart_apply','Apply','text','cart','Apply Coupon'],
  ['cart_checkout_btn','Proceed to Checkout →','text','cart','Checkout Button'],
  ['cart_details','Your Details','text','cart','Details Heading'],
  ['cart_lbl_name','Full Name','text','cart','Name Label'],
  ['cart_lbl_email','Email Address','text','cart','Email Label'],
  ['cart_lbl_phone','WhatsApp / Phone','text','cart','Phone Label'],
  ['cart_lbl_address','Delivery Address','text','cart','Address Label'],
  ['cart_lbl_city','City','text','cart','City Label'],
  ['cart_lbl_postcode','Postcode','text','cart','Postcode Label'],
  ['cart_lbl_notes','Order Notes (Optional)','text','cart','Notes Label'],
  ['cart_pay_heading','Payment Method','text','cart','Payment Heading'],
  ['cart_pay_bank','Bank Transfer','text','cart','Bank Method Label'],
  ['cart_pay_bank_sub','Transfer to our UK bank & upload receipt','text','cart','Bank Method Sub'],
  ['cart_pay_cod','Cash on Delivery','text','cart','COD Method Label'],
  ['cart_pay_cod_sub','Pay when your order arrives','text','cart','COD Method Sub'],
  ['bank_heading','Bank Account Details','text','cart','Bank Details Heading'],
  ['bank_account_name','Robert George Bennett','text','cart','Bank Account Name'],
  ['bank_sort_code','60-84-07','text','cart','Bank Sort Code'],
  ['bank_account_no','70745518','text','cart','Bank Account Number'],
  ['bank_reference_value','Your name only','text','cart','Bank Reference Shown'],
  ['bank_lbl_name','Account Name','text','cart','Bank Name Label'],
  ['bank_lbl_sort','Sort Code','text','cart','Sort Code Label'],
  ['bank_lbl_no','Account No.','text','cart','Account No Label'],
  ['bank_lbl_ref','Reference','text','cart','Reference Label'],
  ['bank_lbl_amount','Amount','text','cart','Amount Label'],
  ['bank_upload_label','Upload Payment Receipt (Optional)','text','cart','Upload Label'],
  ['bank_upload_text','Click to upload your receipt','text','cart','Upload Text'],
  ['bank_ref_input_label','Payment Reference','text','cart','Payment Ref Input Label'],
  ['bank_ref_ph','Enter your first name as payment reference','text','cart','Payment Ref Placeholder'],
  ['bank_ref_hint','Use your first name as the payment reference when making the bank transfer — this helps us identify your payment quickly!','textarea','cart','Payment Ref Hint'],
  ['cart_cod_heading','Cash on Delivery','text','cart','COD Heading'],
  ['cart_amount_due','Amount Due','text','cart','Amount Due Label'],
  ['cart_place_order','Place Order →','text','cart','Place Order Button'],
  ['cart_placing','Placing Order...','text','cart','Placing Order Button'],
  ['cart_back','← Back to Cart','text','cart','Back to Cart'],
  ['cart_activation','Subscription services are active within 1 hour of payment confirmation.','textarea','cart','Checkout Activation'],
  ['cart_err_unavailable','Our system is temporarily unavailable. Please try again in a moment.','textarea','cart','Unavailable Error'],
  ['cart_err_failed','Order could not be placed. Please try again or contact us on WhatsApp or Telegram.','textarea','cart','Failed Error'],
  ['cart_err_network','Network error. Please check your connection and try again.','textarea','cart','Network Error'],
  ['cart_retry','Retry','text','cart','Retry Button'],
  ['cart_wa_btn','WhatsApp Us','text','cart','WhatsApp Help Button'],

  // Success
  ['success_none_title','No order found','text','cart','No Order Title'],
  ['success_none_body','It looks like you navigated here directly.','text','cart','No Order Body'],
  ['success_none_btn','Browse Products','text','cart','No Order Button'],
  ['success_title','Thank you for your order!','text','cart','Success Title'],
  ['success_body','Your order has been received and is being processed. You will receive confirmation once payment is verified. Subscription services are active within 1 hour of payment confirmation.','textarea','cart','Success Body'],
  ['success_order_label','Order Reference','text','cart','Order Reference Label'],
  ['success_items','Order Items','text','cart','Order Items Heading'],
  ['success_cost','Cost Breakdown','text','cart','Cost Heading'],
  ['success_wa','Need Instant Activation? Chat with Support via WhatsApp (Optional)','text','cart','Success WhatsApp CTA'],
  ['success_optional','This is completely optional — your order is already confirmed.','textarea','cart','Success Optional Note'],
  ['success_track','Track My Order →','text','cart','Track Order Button'],
  ['success_track_link','/order-tracking','text','cart','Track Order Link'],

  // Tracking
  ['track_tag','Order Tracking','text','tracking','Page Tag'],
  ['track_title','Track Your Order','text','tracking','Page Title'],
  ['track_subtitle','Enter your Order ID to check the latest status of your order.','textarea','tracking','Page Subtitle'],
  ['track_placeholder','e.g. FK44-62305','text','tracking','Input Placeholder'],
  ['track_btn','Track Order','text','tracking','Track Button'],
  ['track_searching','Searching...','text','tracking','Searching Button'],
  ['track_not_found','Order not found. Please check your Order ID and try again.','text','tracking','Not Found'],
  ['track_status_pending','Pending Verification','text','tracking','Status Pending'],
  ['track_status_confirmed','Confirmed','text','tracking','Status Confirmed'],
  ['track_status_dispatched','Dispatched','text','tracking','Status Dispatched'],
  ['track_status_delivered','Delivered','text','tracking','Status Delivered'],
  ['track_step1_title','Order Received','text','tracking','Step 1 Title'],
  ['track_step1_desc','We have received your order and payment receipt.','textarea','tracking','Step 1 Desc'],
  ['track_step2_title','Payment Verified','text','tracking','Step 2 Title'],
  ['track_step2_desc','Your payment has been verified and order confirmed.','textarea','tracking','Step 2 Desc'],
  ['track_step3_title','Dispatched','text','tracking','Step 3 Title'],
  ['track_step3_desc','Your order is on its way! Delivery in 2-3 working days.','textarea','tracking','Step 3 Desc'],
  ['track_step4_title','Delivered','text','tracking','Step 4 Title'],
  ['track_step4_desc','Your order has been delivered. Enjoy!','textarea','tracking','Step 4 Desc'],
  ['track_help_title','Need Help?','text','tracking','Help Title'],
  ['track_help_body','Cannot find your order or have a question? Chat with us on WhatsApp or Telegram.','textarea','tracking','Help Body'],
  ['track_wa_btn','WhatsApp Us','text','tracking','WhatsApp Button'],

  // Blog
  ['blog_tag','Our Blog','text','blog','Page Tag'],
  ['blog_title','Tips, Guides & Updates','text','blog','Page Title'],
  ['blog_subtitle','Everything you need to get the most out of your devices and subscription plans.','textarea','blog','Page Subtitle'],
  ['blog_read','Read Article →','text','blog','Read Link'],
  ['blog_read_short','Read →','text','blog','Read Short Link'],
  ['blog_newsletter_title','Stay in the Loop','text','blog','Newsletter Title'],
  ['blog_newsletter_sub','Get the latest guides, tips and offers delivered to your inbox.','textarea','blog','Newsletter Subtitle'],
  ['blog_subscribe','Subscribe','text','blog','Subscribe Button'],
  ['blog_subscribed','You are subscribed! Thank you.','text','blog','Subscribed Message'],
  ['blog_back','← Back to Blog','text','blog','Back Link'],
  ['blog_not_found','Post not found. ← Back to Blog','text','blog','Not Found'],
  ['blog_faq_heading','Frequently Asked Questions','text','blog','Post FAQ Heading'],
  ['blog_cta_title','Ready to Shop?','text','blog','Post CTA Title'],
  ['blog_cta_sub','Browse our full range of Firestick devices and Streaming Plans.','textarea','blog','Post CTA Subtitle'],
  ['blog_cta_btn','View Products →','text','blog','Post CTA Button'],
  ['blog_cta_link','/products','text','blog','Post CTA Link'],

  // Legal
  ['privacy_tag','Legal','text','legal','Privacy Tag'],
  ['privacy_title','Privacy Policy','text','legal','Privacy Title'],
  ['privacy_updated','Last updated: 30 May 2026','text','legal','Privacy Updated'],
  ['privacy_body','','textarea','legal','Privacy Body HTML'],
  ['terms_tag','Legal','text','legal','Terms Tag'],
  ['terms_title','Terms & Conditions','text','legal','Terms Title'],
  ['terms_updated','Last updated: 30 May 2026','text','legal','Terms Updated'],
  ['terms_body','','textarea','legal','Terms Body HTML'],
  ['refund_tag','Legal','text','legal','Refund Tag'],
  ['refund_title','Refund Policy','text','legal','Refund Title'],
  ['refund_updated','Last updated: 30 May 2026','text','legal','Refund Updated'],
  ['refund_body','','textarea','legal','Refund Body HTML'],
  ['refund_cta_title','Need Help With a Return?','text','legal','Refund CTA Title'],
  ['refund_cta_sub','Our team is here to help. Contact us via WhatsApp or Telegram for the fastest response.','textarea','legal','Refund CTA Subtitle'],
  ['refund_wa_btn','WhatsApp Us','text','legal','Refund WhatsApp Button'],
  ['refund_email_btn','Email Us','text','legal','Refund Email Button'],

  // Subscription landing page (/iptv-subscriptions-uk)
  ['nav_subscription_label','IPTV Subscription','text','settings','Navbar Subscription Link'],
  ['subscription_hero_eyebrow','UK Streaming Subscriptions','text','subscription','Hero Eyebrow'],
  ['subscription_hero_title','IPTV Subscriptions UK — Flexible Plans for Firestick & Smart Devices','text','subscription','Hero H1'],
  ['subscription_hero_intro','Choose a Firestick4UK streaming subscription that suits your household. Order through our secure checkout, then get setup support from our UK team when you need it.','textarea','subscription','Hero Intro'],
  ['subscription_hero_primary_cta','View Subscription Plans','text','subscription','Hero Primary CTA'],
  ['subscription_hero_wa_cta','Ask on WhatsApp','text','subscription','Hero WhatsApp CTA'],
  ['subscription_benefits_title','Why Choose Firestick4UK','text','subscription','Benefits Title'],
  ['subscription_benefits_intro','Straightforward plans, UK-based help, and a checkout flow you already know from our store.','textarea','subscription','Benefits Intro'],
  ['subscription_benefits_json','[{"icon":"UK","title":"UK-Based Support","desc":"Real help via WhatsApp when you need setup or order assistance."},{"icon":"CK","title":"Simple Checkout","desc":"Order through our existing store with bank transfer or cash on delivery where available."},{"icon":"DV","title":"Device Friendly","desc":"Designed for Firestick / Fire TV and other compatible streaming devices."},{"icon":"AC","title":"Fast Activation","desc":"Subscription services are typically active within 1 hour of payment confirmation."}]','textarea','subscription','Benefits Cards JSON'],
  ['subscription_plans_title','Subscription Plans','text','subscription','Plans Title'],
  ['subscription_plans_intro','Prices and plan details come from our live product catalogue. Pick a plan to view full details or add it to your cart.','textarea','subscription','Plans Intro'],
  ['subscription_plans_cta','View Plan & Buy','text','subscription','Plan Primary CTA'],
  ['subscription_plans_help_cta','Need Help Choosing?','text','subscription','Plan Help WhatsApp CTA'],
  ['subscription_guarantee_text','7-day money-back guarantee available on 1 Year subscription plans and above. Terms apply.','textarea','subscription','Guarantee Wording'],
  ['subscription_product_ids','','textarea','subscription','Selected Product IDs JSON'],
  ['subscription_devices_title','Compatible Devices','text','subscription','Devices Title'],
  ['subscription_devices_intro','Use your subscription on popular streaming devices. Check your model and internet connection before ordering if you are unsure.','textarea','subscription','Devices Intro'],
  ['subscription_devices_json','[{"icon":"FS","title":"Firestick / Fire TV","desc":"Amazon Fire TV Stick and Fire TV devices commonly used with our streaming apps."},{"icon":"TV","title":"Smart TV","desc":"Compatible Smart TVs such as supported Samsung and LG models where the app is available."},{"icon":"AT","title":"Android TV / Android Box","desc":"Android TV devices and Android boxes that support the required player apps."},{"icon":"MB","title":"Mobile & Tablet","desc":"Android phones and tablets, plus iPhone where the supported apps are available."},{"icon":"PC","title":"Windows / Computer","desc":"Windows PCs and compatible computer setups using supported streaming apps."}]','textarea','subscription','Devices Cards JSON'],
  ['subscription_how_title','How It Works','text','subscription','How Title'],
  ['subscription_how_intro','From plan selection to activation — the same ecommerce process used across Firestick4UK.','textarea','subscription','How Intro'],
  ['subscription_how_json','[{"step":"1","title":"Choose a subscription plan","desc":"Compare the plans below and open the plan that fits your needs."},{"step":"2","title":"Place your order in our store","desc":"Add the plan to your cart and complete your delivery and contact details."},{"step":"3","title":"Complete payment","desc":"Pay by UK bank transfer or cash on delivery where offered for your order."},{"step":"4","title":"We confirm your payment","desc":"After payment is verified, your order is confirmed in our system."},{"step":"5","title":"Activation & setup support","desc":"Your subscription is activated and our team can help with setup via WhatsApp if you need it."}]','textarea','subscription','How Steps JSON'],
  ['subscription_rich_title','About IPTV Subscriptions in the UK','text','subscription','Rich Content Title'],
  ['subscription_rich_content','<h2>What is an IPTV subscription in the UK?</h2><p>An IPTV subscription (also described as a UK streaming subscription) gives you access to live TV and on-demand entertainment through compatible apps on devices such as Firestick, Fire TV, Smart TV, Android TV boxes, phones, tablets and Windows computers.</p><p>At Firestick4UK we focus on clear plans, straightforward ordering, and practical support for UK customers. You choose a plan, check out through our store, complete payment, and we help you get set up once the order is confirmed.</p><h2>Who are these TV streaming packages for?</h2><p>Our streaming packages suit households that want a flexible Firestick streaming option without complicated sales processes. Whether you prefer a shorter plan or a longer subscription for better value, you can compare options on this page and buy through the same cart used across the site.</p><h3>Firestick and Fire TV users</h3><p>Many customers use Amazon Firestick or Fire TV as their main living-room device. If you already have a compatible stick or box, a streaming subscription can be a simple way to expand what you watch at home.</p><h3>Smart TV and Android TV</h3><p>If you prefer watching on a Smart TV or Android TV / Android box, check that your device supports the required apps before ordering. Our team can advise on WhatsApp if you are unsure which setup fits your home.</p><h2>Ordering a streaming subscription with Firestick4UK</h2><p>We sell subscription plans as products in our online store. That means plan names, prices and availability stay in sync with the Products admin — when a price changes there, it updates here automatically.</p><ol><li>Select a plan and open the product page or add it to your cart.</li><li>Complete checkout with bank transfer or cash on delivery where available.</li><li>Upload your bank receipt when paying by transfer so we can verify payment quickly.</li><li>After confirmation, activation typically follows within about one hour.</li></ol><h2>Support, activation and refunds</h2><p>Need help choosing a plan or installing an app? Message us on WhatsApp using the buttons on this page. For returns and eligibility rules, always refer to our <a href="/refund-policy">Refund Policy</a>.</p><p>We offer a <strong>7-day money-back guarantee on 1 Year subscription plans and above only</strong>. Shorter plans such as monthly subscriptions are not covered by that guarantee. Terms apply.</p><h3>One connection per subscription</h3><p>Each subscription includes one connection at a time. If you need to watch on two devices at the same time, you will need two separate subscriptions.</p><h2>Looking for IPTV Subscription UK options?</h2><p>If you arrived here searching for IPTV Subscription UK, Firestick streaming, or TV streaming packages, this page is the place to compare Firestick4UK plans, understand compatible devices, and continue into our normal ecommerce checkout — with WhatsApp assistance available whenever you need a hand.</p>','textarea','subscription','Rich SEO HTML'],
  ['subscription_faq_title','Frequently Asked Questions','text','subscription','FAQ Title'],
  ['subscription_faq_intro','Answers are managed in the central FAQ manager. Editing a FAQ there updates this page automatically.','textarea','subscription','FAQ Intro'],
  ['subscription_faq_ids','[11,12,18,19,17,20,2,14]','textarea','subscription','Selected FAQ IDs JSON'],
  ['subscription_cta_title','Ready to start your subscription?','text','subscription','Final CTA Title'],
  ['subscription_cta_desc','Pick a plan above to continue through our store, or message us on WhatsApp if you would like help choosing.','textarea','subscription','Final CTA Description'],
  ['subscription_cta_primary','View Subscription Plans','text','subscription','Final CTA Purchase'],
  ['subscription_cta_wa','Chat on WhatsApp','text','subscription','Final CTA WhatsApp'],
  ['subscription_meta_title','IPTV Subscriptions UK | Firestick Streaming Plans | Firestick4UK','text','subscription','SEO Title'],
  ['subscription_meta_description','Compare Firestick4UK IPTV subscriptions and UK streaming plans for Firestick, Smart TV and Android devices. Order online with UK support.','textarea','subscription','Meta Description'],
  ['subscription_focus_keyword','IPTV Subscription UK','text','subscription','Focus Keyword'],
  ['subscription_canonical','https://firestick4uk.com/iptv-subscriptions-uk/','text','subscription','Canonical URL'],
  ['subscription_og_image','','image','subscription','OG Image URL'],
];
